server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # use compression
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_vary on;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/markdown
        application/json
        application/javascript
        application/octet-stream
        image/svg+xml;

    # / -> shows index page
    location = / {
        try_files /index.html =404;
    }

    # /Other/curl/ -> /Other/curl
    location ~ ^(.+)/$ {
        try_files $uri @strip_slash;
    }
    location @strip_slash {
        rewrite ^(.+)/$ $1 permanent;
    }

    # /Other/curl.html -> /Other/curl
    location ~ ^(.+)\.html$ {
        return 301 $1;
    }

    location / {
        try_files $uri $uri.html $uri/index.html =404;
    }

    # show 404 page on error
    error_page 403 404 /404.html;
    location = /404.html {
        internal;
    }
}
