server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^(.+)\.html$ {
        return 301 $1;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}